CREATE DATABASE IF NOT EXISTS sistema_bancario;
USE sistema_bancario;
DROP TABLE IF EXISTS Clientes_PJ;
DROP TABLE IF EXISTS Clientes_PF;
DROP Table IF EXISTS Clientes;
DROP TABLE IF EXISTS Transacoes;
DROP TABLE IF EXISTS Contas;